#ifndef  __MACRO_WINDOWS_DEFINE_HH
#define  __MACRO_WINDOWS_DEFINE_HH

#define KEYBOARD_MESSAGE_BASIC KEYBOARD_MESSAGE_KEYDOWN
#define KEYBOARD_MESSAGE_KEYDOWN 0x0100
#define KEYBOARD_MESSAGE_KEYUP 0x0101
#define KEYBOARD_MESSAGE_SYSTEM_KEYDOWN 0x0102
#define KEYBOARD_MESSAGE_SYSTEM_UP 0x0103
#define KEYBOARD_PREVIOUSR_STATUS (1u << 30)
#define KEYBOARD_TRANSITION_STATUS (1u << 31)
#endif /*  __MACRO_WINDOWS_DEFINE_HH */

