#ifndef  __MACRO_WINDOWS_DEFINE_HH
#define  __MACRO_WINDOWS_DEFINE_HH

#define KEYBOARD_MESSAGE_BASIC 0x0100
#define KEYBOARD_PREVIOUSR_STATUS (1u << 30)
#define KEYBOARD_TRANSITION_STATUS (1u << 31)
#endif /*  __MACRO_WINDOWS_DEFINE_HH */

